
* Introduction

  This document describes external dependencies and how I think I
  should be tracking them.  It is a bit outdated as of 
  <2012-10-04 Thu> but hopefully that will be fixed soon.

* Getting required external files.

** external DARCS

#+begin_src sh
   darcs get http://common-lisp.net/project/lift/darcs
   cd lift.darcs ; darcs pull
   darcs get http://common-linsp.net/project/cffi/darcs/cffi
   cd cffi.darcs ; darcs pull
#+end_src

   We can use darcs-to-git script to convert (findable on github), and
   ideally upload to GitHub, CommonLisp.net, or repo Git
   public-repository repositories.

   IS THIS A GOOD IDEA?  Once it is there, we can register as a
   submodule, and then use git submodule commands to get the versions
   we need to use.

   I think it's a good idea, only for core development.  For
   developers of CLS programs (away from core), provide the core
   packages and have people develop on top of them.

** Commands for external GIT:

#+begin_src sh
  cd $(LISPSTAT-GIT-TOPLEVEL-DIR) # from here, cd .. (hopefully!)
  git submodule add git://cyrusharmon.org/pub/git/ch-asdf.git \
      	external/ch-asdf.git
  git submodule add git://cyrusharmon.org/pub/git/ch-util.git \
      	external/ch-util.git
  git submodule status
  git status

  ## How do we update locally?   
  ## git submodule update ...??  (test using the submodule that we need to get when connected).
#+end src

* Discussion
